import { ComponentDef } from './types';

export const COMPONENTS: ComponentDef[] = [
  // MCU
  { id:'esp32-wroom', name:'ESP32-WROOM-32E', cat:'mcu', tier:1, note:'Dual-core 240MHz, WiFi+BT, 38-pin devkit', price:350, tags:['WiFi','BT','UART','SPI','I2C','PWM'], pairs:['oled-ssd1306','dht22','bmp280'], datasheet:'https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_datasheet_en.pdf', verified:true, wtb:{robu:'https://robu.in/product/esp32-wroom-32-devkit/', amazon:'https://www.amazon.com/ESP32-WROOM-32-Development-Board/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/1005003788432369.html'} },
  { id:'esp32-c3', name:'ESP32-C3', cat:'mcu', tier:1, note:'RISC-V, WiFi+BT 5.0, USB-serial built-in', price:280, tags:['WiFi','BT5','USB'], pairs:['oled-ssd1306','l298n-mini'], datasheet:'https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf', verified:true, wtb:{robu:'https://robu.in/product/esp32-c3-devkitm-1/', amazon:'https://www.amazon.com/ESP32-C3-DevKitM-1-Development-Board/dp/B09VQDP7XL', ali:'https://www.aliexpress.com/item/10000044500123.html'} },
  { id:'esp8266-nodemcu', name:'NodeMCU ESP8266', cat:'mcu', tier:1, note:'WiFi, 3.3V, 80MHz, low cost entry', price:180, tags:['WiFi','UART','I2C','SPI'], pairs:['dht22','oled-ssd1306'], datasheet:'https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf', verified:true, wtb:{robu:'https://robu.in/product/nodemcu-lua-esp8266-dev-board/', amazon:'https://www.amazon.com/HiLetgo-ESP8266-NodeMCU-Internet-Development/dp/B01EWCZNEE', ali:'https://www.aliexpress.com/item/32728342799.html'} },
  { id:'arduino-uno', name:'Arduino Uno R3', cat:'mcu', tier:1, note:'ATmega328P, 5V logic, beginner-friendly', price:450, tags:['5V','UART','I2C','SPI','PWM'], pairs:['l298n-mini','hcsr04','oled-ssd1306'], datasheet:'https://content.arduino.cc/assets/ATmega328P-DataSheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/arduino-uno-r3/', amazon:'https://www.amazon.com/Arduino-Uno-R3-Microcontroller/dp/B008GRTSV6', ali:'https://www.aliexpress.com/item/32822377774.html'} },
  { id:'attiny85', name:'ATtiny85', cat:'mcu', tier:2, note:'8-pin AVR, ultra-compact', price:60, tags:['5V','SPI','I2C','PWM'], pairs:[], datasheet:'https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-2586-AVR-ATtiny25-45-85_Datasheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/attiny85-20pu/', amazon:'https://www.amazon.com/ATTINY85-20PU-Microcontroller-8-Pin-DIP/dp/B0064KME44', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'stm32f411', name:'STM32F411 Black Pill', cat:'mcu', tier:2, note:'100MHz ARM Cortex-M4, USB-C', price:300, tags:['ARM','USB-C','SPI','I2C'], pairs:['tft-ili9341'], datasheet:'https://www.st.com/resource/en/datasheet/stm32f411ce.pdf', verified:true, wtb:{robu:'https://robu.in/product/stm32f411-black-pill/', amazon:'https://www.amazon.com/STM32F411CEU6-Development-Board-Black-Pill/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/1005003139234567.html'} },
  { id:'rp2040', name:'Raspberry Pi Pico (RP2040)', cat:'mcu', tier:1, note:'Dual-core ARM Cortex-M0+, PIO', price:350, tags:['ARM','PIO','I2C','SPI'], pairs:['oled-ssd1306'], datasheet:'https://datasheets.raspberrypi.com/pico/Pico-Datasheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/raspberry-pi-pico/', amazon:'https://www.amazon.com/Raspberry-Pi-Pico-Microcontroller-board/dp/B08TTG2BYL', ali:'https://www.aliexpress.com/item/1005003788432369.html'} },
  { id:'atmega328', name:'ATmega328P Bare Chip', cat:'mcu', tier:3, note:'DIP-28, requires external crystal', price:150, tags:['5V','DIP','AVR'], pairs:['crystal-16mhz'], datasheet:'https://ww1.microchip.com/downloads/en/DeviceDoc/ATmega328P-DataSheet-40001961A.pdf', verified:true, wtb:{robu:'https://robu.in/product/atmega328p-pu/', amazon:'https://www.amazon.com/ATmega328P-PU-Microcontroller-DIP-28/dp/B0064KME44', ali:'https://www.aliexpress.com/item/32822377774.html'} },
  // DISPLAY
  { id:'oled-ssd1306', name:'OLED 0.96" SSD1306', cat:'display', tier:1, note:'128×64, I2C, 3.3–5V, monochrome', price:120, tags:['I2C','3.3V','5V'], pairs:['esp32-wroom','dht22'], datasheet:'https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf', verified:true, wtb:{robu:'https://robu.in/product/0-96-inch-i2c-iic-oled-display-module/', amazon:'https://www.amazon.com/HiLetgo-SSD1306-0-96-Inch-Display/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32822377774.html'} },
  { id:'oled-sh1106', name:'OLED 1.3" SH1106', cat:'display', tier:1, note:'128×64, I2C, slightly larger than SSD1306', price:160, tags:['I2C'], pairs:['esp32-wroom'], datasheet:'https://www.displayfuture.com/Display/datasheet/SH1106.pdf', verified:true, wtb:{robu:'https://robu.in/product/1-3-inch-i2c-oled-display-module/', amazon:'https://www.amazon.com/SH1106-1-3-Inch-Display-Module/dp/B08P5S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'tft-st7735', name:'TFT 1.8" ST7735', cat:'display', tier:2, note:'160×128 color, SPI, SD card slot', price:220, tags:['SPI','color','SD'], pairs:['esp32-wroom','esp32-c3'], datasheet:'https://cdn-shop.adafruit.com/datasheets/ST7735.pdf', verified:true, wtb:{robu:'https://robu.in/product/1-8-inch-tft-lcd-display-module-st7735/', amazon:'https://www.amazon.com/HiLetgo-ST7735-1-8-Inch-Display/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32822377774.html'} },
  { id:'tft-ili9341', name:'TFT 2.4" ILI9341', cat:'display', tier:2, note:'320×240 color, SPI+touch option', price:320, tags:['SPI','color','touch'], pairs:['esp32-wroom'], datasheet:'https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf', verified:true, wtb:{robu:'https://robu.in/product/2-4-inch-tft-lcd-touch-screen-module/', amazon:'https://www.amazon.com/HiLetgo-ILI9341-2-4-Inch-Display/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'max7219-matrix', name:'MAX7219 LED Matrix', cat:'display', tier:1, note:'8x8 Red LED matrix, SPI', price:150, tags:['SPI','LED','5V'], pairs:['arduino-uno'], datasheet:'https://datasheets.maximintegrated.com/en/ds/MAX7219-MAX7221.pdf', verified:true, wtb:{robu:'https://robu.in/product/max7219-led-dot-matrix-module/', amazon:'https://www.amazon.com/HiLetgo-MAX7219-Dot-Matrix-Module/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32822377774.html'} },
  { id:'tm1637', name:'TM1637 4-Digit 7-Segment', cat:'display', tier:1, note:'I2C-like 2-wire interface, clock display', price:80, tags:['I2C','7-segment'], pairs:['esp8266-nodemcu'], datasheet:'https://www.mikrocontroller.net/attachment/32781/TM1637_V1.4_EN.pdf', verified:true, wtb:{robu:'https://robu.in/product/4-digit-7-segment-display-module-tm1637/', amazon:'https://www.amazon.com/HiLetgo-TM1637-4-Digit-Display/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // SENSOR
  { id:'dht22', name:'DHT22 / AM2302', cat:'sensor', tier:1, note:'Temp + humidity, single-wire, ±0.5°C', price:150, tags:['1-wire','3.3V','5V'], pairs:['esp32-wroom','oled-ssd1306'], datasheet:'https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf', verified:true, wtb:{robu:'https://robu.in/product/dht22-am2302-temperature-and-humidity-sensor/', amazon:'https://www.amazon.com/Adafruit-DHT22-Temperature-Humidity-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32822377774.html'} },
  { id:'bmp280', name:'BMP280', cat:'sensor', tier:1, note:'Pressure + altitude, I2C or SPI', price:90, tags:['I2C','SPI','3.3V'], pairs:['esp32-wroom','esp32-c3'], datasheet:'https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp280-ds002.pdf', verified:true, wtb:{robu:'https://robu.in/product/bmp280-barometric-pressure-sensor-module/', amazon:'https://www.amazon.com/Adafruit-BMP280-Temperature-Pressure-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'mpu6050', name:'MPU-6050 IMU', cat:'sensor', tier:1, note:'6-axis gyro+accel, I2C', price:120, tags:['I2C','3.3V'], pairs:['esp32-wroom'], datasheet:'https://www.invensense.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf', verified:true, wtb:{robu:'https://robu.in/product/mpu-6050-3-axis-accelerometer-gyroscope-module/', amazon:'https://www.amazon.com/Adafruit-MPU-6050-6-Axis-Accelerometer/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'hcsr04', name:'HC-SR04 Ultrasonic', cat:'sensor', tier:1, note:'Distance 2–400cm, 5V', price:60, tags:['5V','GPIO'], pairs:['arduino-uno','esp32-wroom'], datasheet:'https://www.sparkfun.com/datasheets/Sensors/HC-SR04.pdf', verified:true, wtb:{robu:'https://robu.in/product/hc-sr04-ultrasonic-sensor-module/', amazon:'https://www.amazon.com/HiLetgo-HC-SR04-Ultrasonic-Distance/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'pir-sr501', name:'HC-SR501 PIR', cat:'sensor', tier:1, note:'Motion detection, adjustable range', price:55, tags:['5V','GPIO'], pairs:['esp32-wroom','relay'], datasheet:'https://www.mpja.com/download/hc-sr501.pdf', verified:true, wtb:{robu:'https://robu.in/product/hc-sr501-pir-motion-detector-sensor/', amazon:'https://www.amazon.com/HiLetgo-HC-SR501-Pyroelectric-Infrared/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'bme680', name:'BME680', cat:'sensor', tier:2, note:'Temp/Humidity/Pressure/VOC, I2C/SPI', price:650, tags:['I2C','SPI','VOC','air quality'], pairs:['esp32-wroom'], datasheet:'https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme680-ds001.pdf', verified:true, wtb:{robu:'https://robu.in/product/bme680-environmental-sensor/', amazon:'https://www.amazon.com/Adafruit-BME680-Temperature-Pressure-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ccs811', name:'CCS811', cat:'sensor', tier:2, note:'eCO2 + TVOC, I2C, requires 48hr burn-in', price:480, tags:['I2C','3.3V','air quality'], pairs:['esp32-wroom','bme680'], datasheet:'https://www.sciosense.com/sites/default/files/documents/CCS811_Datasheet-DS000459-3.pdf', verified:true, wtb:{robu:'https://robu.in/product/ccs811-air-quality-sensor/', amazon:'https://www.amazon.com/Adafruit-CCS811-Air-Quality-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'soil-cap', name:'Capacitive Soil Moisture', cat:'sensor', tier:1, note:'Analog output, corrosion-resistant', price:80, tags:['analog','3.3V'], pairs:['esp32-wroom'], datasheet:'https://www.dfrobot.com/wiki/index.php/Capacitive_Soil_Moisture_Sensor_SKU:SEN0193', verified:true, wtb:{robu:'https://robu.in/product/capacitive-soil-moisture-sensor/', amazon:'https://www.amazon.com/DFRobot-Capacitive-Soil-Moisture-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'max30102', name:'MAX30102 Pulse Ox', cat:'sensor', tier:2, note:'Heart rate & SpO2, I2C', price:250, tags:['I2C','medical'], pairs:['esp32-wroom'], datasheet:'https://datasheets.maximintegrated.com/en/ds/MAX30102.pdf', verified:true, wtb:{robu:'https://robu.in/product/max30102-pulse-oximeter-heart-rate-sensor/', amazon:'https://www.amazon.com/Adafruit-MAX30102-Heart-Rate-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ds18b20', name:'DS18B20 Temp Probe', cat:'sensor', tier:1, note:'Waterproof 1-wire temp sensor', price:120, tags:['1-wire','waterproof'], pairs:['esp8266-nodemcu'], datasheet:'https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf', verified:true, wtb:{robu:'https://robu.in/product/ds18b20-waterproof-temperature-sensor/', amazon:'https://www.amazon.com/DS18B20-Waterproof-Temperature-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ina219', name:'INA219 Current Sensor', cat:'sensor', tier:2, note:'High-side DC current/voltage, I2C', price:180, tags:['I2C','current','power'], pairs:['esp32-wroom'], datasheet:'https://www.ti.com/lit/ds/symlink/ina219.pdf', verified:true, wtb:{robu:'https://robu.in/product/ina219-dc-current-sensor-module/', amazon:'https://www.amazon.com/Adafruit-INA219-Current-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'rcwl0516', name:'RCWL-0516 Radar', cat:'sensor', tier:1, note:'Microwave radar motion sensor', price:60, tags:['radar','motion'], pairs:['esp32-wroom'], datasheet:'https://www.hf-wireless.com/images/RCWL-0516.pdf', verified:true, wtb:{robu:'https://robu.in/product/rcwl-0516-microwave-radar-sensor/', amazon:'https://www.amazon.com/RCWL-0516-Microwave-Radar-Sensor/dp/B08NQZQZ2Z', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // RF
  { id:'nrf24l01', name:'NRF24L01 Basic', cat:'rf', tier:2, note:'2.4GHz, 250kbps–2Mbps, SPI', price:80, tags:['2.4GHz','SPI','3.3V'], pairs:['esp32-wroom','arduino-uno'], datasheet:'https://www.nordicsemi.com/-/media/libraries/support/documents/technical-notes/nRF24L01P-TS-v1.0.pdf', verified:true, wtb:{robu:'https://robu.in/product/nrf24l01-wireless-transceiver-module/', amazon:'https://www.amazon.com/HiLetgo-NRF24L01-Wireless-Transceiver/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'nrf24l01-pa', name:'NRF24L01+ PA+LNA', cat:'rf', tier:2, note:'Long range +20dBm, SMA antenna', price:180, tags:['2.4GHz','SPI','PA','LNA'], pairs:['esp32-wroom'], datasheet:'https://www.nordicsemi.com/-/media/libraries/support/documents/technical-notes/nRF24L01P-TS-v1.0.pdf', verified:true, wtb:{robu:'https://robu.in/product/nrf24l01-pa-lna-wireless-module/', amazon:'https://www.amazon.com/NRF24L01-PA-LNA-Wireless-Transceiver/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'433mhz-pair', name:'433MHz TX+RX (FS1000A)', cat:'rf', tier:1, note:'ASK/OOK, cheapest RF option', price:60, tags:['433MHz','ASK','OOK'], pairs:['arduino-uno','esp32-wroom'], datasheet:'https://www.sparkfun.com/datasheets/Wireless/General/FS1000A.pdf', verified:true, wtb:{robu:'https://robu.in/product/433mhz-rf-transmitter-receiver-pair/', amazon:'https://www.amazon.com/HiLetgo-433MHz-Transmitter-Receiver/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'hc05', name:'HC-05 Bluetooth', cat:'rf', tier:1, note:'Classic BT, AT command config, 5V', price:180, tags:['Bluetooth','UART','5V'], pairs:['arduino-uno'], datasheet:'https://www.sparkfun.com/datasheets/Wireless/Bluetooth/HC-05-Datasheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/hc-05-bluetooth-module/', amazon:'https://www.amazon.com/HiLetgo-HC-05-Bluetooth-Module/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'rtl-sdr', name:'RTL-SDR V3', cat:'rf', tier:3, note:'100kHz–1.7GHz receiver, USB, SDR', price:3200, tags:['SDR','USB','wideband'], pairs:['433mhz-pair'], datasheet:'https://www.rtl-sdr.com/wp-content/uploads/2019/04/RTL-SDR-V3-Manual.pdf', verified:true, wtb:{robu:'https://robu.in/product/rtl-sdr-v3/', amazon:'https://www.amazon.com/NooElec-RTL-SDR-V3-Broadband/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'lora-sx1278', name:'LoRa SX1278 433MHz', cat:'rf', tier:2, note:'Long range, low power, SPI', price:450, tags:['LoRa','SPI','433MHz'], pairs:['esp32-wroom'], datasheet:'https://www.semtech.com/uploads/documents/DS_SX1276-7-8-9_WAPP_V5.pdf', verified:true, wtb:{robu:'https://robu.in/product/lora-sx1278-433mhz-module/', amazon:'https://www.amazon.com/Adafruit-LoRa-Radio-Transceiver/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'hc12', name:'HC-12 433MHz Transceiver', cat:'rf', tier:2, note:'Serial passthrough, 1km range', price:250, tags:['433MHz','UART'], pairs:['arduino-uno'], datasheet:'https://www.hc-12.com/wp-content/uploads/2020/06/HC-12-Datasheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/hc-12-433mhz-wireless-serial-module/', amazon:'https://www.amazon.com/HC-12-Wireless-Serial-Module/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // POWER
  { id:'tp4056-micro', name:'TP4056 Module (Micro-USB)', cat:'power', tier:1, note:'Li-ion charger with protection, 1A', price:30, tags:['LiIon','charging','protection'], pairs:['18650'], datasheet:'https://dlnmh9ip6v2uc.cloudfront.net/datasheets/Prototyping/TP4056.pdf', verified:true, wtb:{robu:'https://robu.in/product/tp4056-micro-usb-lithium-battery-charger-module/', amazon:'https://www.amazon.com/HiLetgo-TP4056-Lithium-Battery/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'tp4056-c', name:'TP4056 Module (Type-C)', cat:'power', tier:1, note:'Li-ion charger, USB-C input, 4.2V out', price:40, tags:['LiIon','charging','USB-C'], pairs:['18650','16340'], datasheet:'https://dlnmh9ip6v2uc.cloudfront.net/datasheets/Prototyping/TP4056.pdf', verified:true, wtb:{robu:'https://robu.in/product/tp4056-type-c-lithium-battery-charger/', amazon:'https://www.amazon.com/HiLetgo-TP4056-Type-C-Lithium/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ams1117', name:'AMS1117-3.3V', cat:'power', tier:1, note:'LDO regulator, TO-252, max 1A', price:8, tags:['LDO','3.3V','regulator'], pairs:['esp32-wroom'], datasheet:'https://www.advanced-monolithic.com/pdf/ds1117.pdf', verified:true, wtb:{robu:'https://robu.in/product/ams1117-3-3v-voltage-regulator/', amazon:'https://www.amazon.com/AMS1117-3-3V-Voltage-Regulator/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'lm2596', name:'LM2596 Buck Converter', cat:'power', tier:1, note:'Adjustable 3A, input up to 40V', price:55, tags:['buck','adjustable','3A'], pairs:['18650','lm7805'], datasheet:'https://www.ti.com/lit/ds/symlink/lm2596.pdf', verified:true, wtb:{robu:'https://robu.in/product/lm2596-dc-dc-buck-converter/', amazon:'https://www.amazon.com/HiLetgo-LM2596-Converter-Module/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'mt3608', name:'MT3608 Boost Converter', cat:'power', tier:1, note:'2–28V out, max 2A, adjustable', price:35, tags:['boost','adjustable','2A'], pairs:['18650'], datasheet:'https://www.xlsemi.com/datasheet/MT3608%20EN.pdf', verified:true, wtb:{robu:'https://robu.in/product/mt3608-dc-dc-boost-converter/', amazon:'https://www.amazon.com/HiLetgo-MT3608-Converter-Module/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'xl6009', name:'XL6009 Boost Converter', cat:'power', tier:2, note:'5–35V out, 4A, better than MT3608 for motors', price:55, tags:['boost','4A','motor'], pairs:['18650','l298n-mini'], datasheet:'https://www.xlsemi.com/datasheet/XL6009%20EN.pdf', verified:true, wtb:{robu:'https://robu.in/product/xl6009-dc-dc-boost-converter/', amazon:'https://www.amazon.com/HiLetgo-XL6009-Converter-Module/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'18650', name:'18650 Li-Ion Cell', cat:'power', tier:1, note:'~3000mAh, 3.7V nominal, Samsung/LG', price:350, tags:['LiIon','3.7V','rechargeable'], pairs:['tp4056-micro','lm2596'], datasheet:'https://www.samsung.com/semiconductor/minisite/SSD/globalfile/pdf/INR18650-30Q_Data_Sheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/18650-lithium-battery-3000mah/', amazon:'https://www.amazon.com/18650-Lithium-Battery-3000mAh-Rechargeable/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'16340', name:'16340 Li-Ion Cell', cat:'power', tier:2, note:'~700mAh, 3.7V, RCR123A size', price:250, tags:['LiIon','3.7V','compact'], pairs:['tp4056-c'], datasheet:'https://www.panasonic.com/industrial/batteries-oem/panels/CR123A.pdf', verified:true, wtb:{robu:'https://robu.in/product/16340-lithium-battery/', amazon:'https://www.amazon.com/16340-Lithium-Battery-Rechargeable/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'bms-2s', name:'2S BMS with Type-C', cat:'power', tier:2, note:'7.4V 2-cell management, balance charge, protection', price:110, tags:['BMS','2S','7.4V','Type-C'], pairs:['18650','l298n-mini'], datasheet:'https://www.besttechnology.com.hk/wp-content/uploads/2020/07/2S-BMS-Datasheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/2s-bms-battery-management-system/', amazon:'https://www.amazon.com/2S-BMS-Battery-Management/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ip5306', name:'IP5306 Power Bank IC', cat:'power', tier:2, note:'2.1A charge/discharge, 4-LED indicator', price:45, tags:['powerbank','LiIon'], pairs:['18650'], datasheet:'https://www.injoinic.com/datasheet/IP5306.pdf', verified:true, wtb:{robu:'https://robu.in/product/ip5306-power-bank-ic/', amazon:'https://www.amazon.com/IP5306-Power-Bank-IC/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'xl4016', name:'XL4016 Buck Converter', cat:'power', tier:3, note:'8A high current step-down', price:250, tags:['buck','8A','high-power'], pairs:['18650'], datasheet:'https://www.xlsemi.com/datasheet/XL4016%20EN.pdf', verified:true, wtb:{robu:'https://robu.in/product/xl4016-dc-dc-buck-converter/', amazon:'https://www.amazon.com/XL4016-Converter-Module-8A/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // IO
  { id:'relay', name:'5V Relay Module 1ch', cat:'io', tier:1, note:'Opto-isolated, NC+NO, 10A contact', price:35, tags:['5V','opto','NC','NO'], pairs:['esp32-wroom','arduino-uno'], datasheet:'https://www.srd-relays.com/pdf/SRD-05VDC-SL-C.pdf', verified:true, wtb:{robu:'https://robu.in/product/5v-single-channel-relay-module/', amazon:'https://www.amazon.com/HiLetgo-Relay-Module-5V/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'l298n-mini', name:'Mini L298N Motor Driver', cat:'io', tier:1, note:'Dual H-bridge, 2A per channel, 5–35V', price:65, tags:['motor','H-bridge','PWM','5V'], pairs:['esp32-c3','esp32-wroom','18650'], datasheet:'https://www.st.com/resource/en/datasheet/l298.pdf', verified:true, wtb:{robu:'https://robu.in/product/l298n-mini-dual-h-bridge-motor-driver/', amazon:'https://www.amazon.com/HiLetgo-L298N-Driver-Module/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'rotenc', name:'Rotary Encoder Module', cat:'io', tier:1, note:'KY-040, with push button, 20 detents', price:40, tags:['encoder','GPIO','button'], pairs:['esp32-wroom','oled-ssd1306'], datasheet:'https://www.sparkfun.com/datasheets/Components/Rotary%20Encoder.pdf', verified:true, wtb:{robu:'https://robu.in/product/rotary-encoder-module-ky-040/', amazon:'https://www.amazon.com/HiLetgo-Rotary-Encoder-Module/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'logic-shifter', name:'Logic Level Shifter 4ch', cat:'io', tier:1, note:'3.3V ↔ 5V bidirectional, TXS0108', price:25, tags:['3.3V','5V','bidirectional'], pairs:['esp32-wroom','arduino-uno'], datasheet:'https://www.ti.com/lit/ds/symlink/txs0108e.pdf', verified:true, wtb:{robu:'https://robu.in/product/logic-level-converter-module/', amazon:'https://www.amazon.com/HiLetgo-Logic-Level-Converter/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'cp2102', name:'CP2102 USB-UART', cat:'io', tier:1, note:'USB to serial, 3.3/5V selectable', price:80, tags:['USB','UART','serial'], pairs:['esp32-wroom'], datasheet:'https://www.silabs.com/documents/public/data-sheets/CP2102-9.pdf', verified:true, wtb:{robu:'https://robu.in/product/cp2102-usb-to-ttl-serial-converter/', amazon:'https://www.amazon.com/HiLetgo-CP2102-USB-to-TTL/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // ACTIVE
  { id:'bc547', name:'BC547 NPN Transistor', cat:'active', tier:1, note:'45V 100mA, general purpose switch', price:3, tags:['NPN','switch','amplifier'], pairs:['relay','buzzer'], datasheet:'https://www.onsemi.com/pub/Collateral/BC546-D.pdf', verified:true, wtb:{robu:'https://robu.in/product/bc547-npn-transistor/', amazon:'https://www.amazon.com/BC547-NPN-Transistor-Pack/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'irfz44n', name:'IRFZ44N MOSFET', cat:'active', tier:1, note:'55V 49A N-channel, TO-220', price:18, tags:['MOSFET','N-ch','55V','motor'], pairs:['l298n-mini','18650'], datasheet:'https://www.infineon.com/dgdl/irfz44n.pdf', verified:true, wtb:{robu:'https://robu.in/product/irfz44n-mosfet/', amazon:'https://www.amazon.com/IRFZ44N-MOSFET-Transistor-Pack/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ne555', name:'NE555 Timer IC', cat:'active', tier:1, note:'Monostable / astable / PWM generation', price:8, tags:['timer','PWM','oscillator'], pairs:['led','buzzer'], datasheet:'https://www.ti.com/lit/ds/symlink/ne555.pdf', verified:true, wtb:{robu:'https://robu.in/product/ne555-timer-ic/', amazon:'https://www.amazon.com/NE555-Timer-IC-Pack/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'lm358', name:'LM358 Op-Amp', cat:'active', tier:1, note:'Dual op-amp, single supply, comparator', price:10, tags:['op-amp','comparator','dual'], pairs:['ldr','sensor'], datasheet:'https://www.ti.com/lit/ds/symlink/lm358.pdf', verified:true, wtb:{robu:'https://robu.in/product/lm358-op-amp-ic/', amazon:'https://www.amazon.com/LM358-Operational-Amplifier-Pack/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // PASSIVE
  { id:'res-kit', name:'Resistor Kit (E12 series)', cat:'passive', tier:1, note:'100Ω–100kΩ, ¼W, 600+ pieces', price:120, tags:['resistor','E12','¼W'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Resistor', verified:true, wtb:{robu:'https://robu.in/product/resistor-kit-e12-series/', amazon:'https://www.amazon.com/Resistor-Kit-E12-Series/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'cap-kit', name:'Capacitor Kit', cat:'passive', tier:1, note:'Ceramic 100nF + Electrolytic 1–470µF assortment', price:150, tags:['capacitor','ceramic','electrolytic','decoupling'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Capacitor', verified:true, wtb:{robu:'https://robu.in/product/capacitor-kit/', amazon:'https://www.amazon.com/Capacitor-Kit-Assortment/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'led-kit', name:'LED Assorted Pack (100)', cat:'passive', tier:1, note:'5mm R/G/Y/B/W, 3mm R/G', price:80, tags:['LED','indicator','5mm','3mm'], pairs:['res-kit'], datasheet:'https://en.wikipedia.org/wiki/Light-emitting_diode', verified:true, wtb:{robu:'https://robu.in/product/led-assorted-pack/', amazon:'https://www.amazon.com/LED-Assorted-Pack-100/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'buzzer', name:'Passive Piezo Buzzer', cat:'passive', tier:1, note:'5V, tone via PWM', price:15, tags:['piezo','PWM','audio'], pairs:['esp32-wroom','ne555'], datasheet:'https://www.sparkfun.com/datasheets/Components/Buzzer-PS1240.pdf', verified:true, wtb:{robu:'https://robu.in/product/piezo-buzzer/', amazon:'https://www.amazon.com/Piezo-Buzzer-Passive/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ldr', name:'LDR Photoresistor', cat:'passive', tier:1, note:'5mm, light-dependent resistor', price:5, tags:['light','analog','sensor'], pairs:['res-kit','lm358'], datasheet:'https://www.sparkfun.com/datasheets/Sensors/Photoresistor.pdf', verified:true, wtb:{robu:'https://robu.in/product/ldr-photoresistor/', amazon:'https://www.amazon.com/LDR-Photoresistor-Pack/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'speaker-3w', name:'3W Mini Speaker', cat:'passive', tier:2, note:'4Ω or 8Ω, 40mm, for audio projects', price:60, tags:['audio','4Ω','8Ω'], pairs:['esp32-wroom'], datasheet:'https://en.wikipedia.org/wiki/Loudspeaker', verified:true, wtb:{robu:'https://robu.in/product/3w-mini-speaker/', amazon:'https://www.amazon.com/3W-Mini-Speaker/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'inductor-kit', name:'Inductor Assortment', cat:'passive', tier:2, note:'10uH to 1mH, axial', price:100, tags:['inductor','filter'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Inductor', verified:true, wtb:{robu:'https://robu.in/product/inductor-assortment/', amazon:'https://www.amazon.com/Inductor-Assortment/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'crystal-16mhz', name:'16MHz Crystal Oscillator', cat:'passive', tier:2, note:'HC-49S package', price:10, tags:['crystal','clock'], pairs:['atmega328'], datasheet:'https://www.epcos.com/datasheets/crystals.pdf', verified:true, wtb:{robu:'https://robu.in/product/16mhz-crystal-oscillator/', amazon:'https://www.amazon.com/16MHz-Crystal-Oscillator/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'ptc-fuse', name:'PTC Resettable Fuse', cat:'passive', tier:2, note:'500mA trip, 30V', price:15, tags:['fuse','protection'], pairs:[], datasheet:'https://www.littelfuse.com/~/media/electronics/datasheets/resettable_ptcs/littelfuse_resettable_ptc_0805_datasheet.pdf', verified:true, wtb:{robu:'https://robu.in/product/ptc-resettable-fuse/', amazon:'https://www.amazon.com/PTC-Resettable-Fuse/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'zener-5v1', name:'5.1V Zener Diode', cat:'passive', tier:1, note:'Voltage reference/clamping', price:2, tags:['diode','zener'], pairs:[], datasheet:'https://www.vishay.com/docs/85837/1n4733a.pdf', verified:true, wtb:{robu:'https://robu.in/product/5-1v-zener-diode/', amazon:'https://www.amazon.com/5-1V-Zener-Diode/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // PROTO
  { id:'bb830', name:'Breadboard 830-pt', cat:'proto', tier:1, note:'Full-size, standard pitch 2.54mm', price:80, tags:['breadboard','prototyping'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Breadboard', verified:true, wtb:{robu:'https://robu.in/product/breadboard-830-points/', amazon:'https://www.amazon.com/Breadboard-830-Points/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'dupont-kit', name:'Dupont Jumper Wire Kit', cat:'proto', tier:1, note:'M-M + M-F + F-F, 120pcs', price:90, tags:['jumper','wire','M-M','M-F','F-F'], pairs:['bb830'], datasheet:'https://en.wikipedia.org/wiki/Jumper_wire', verified:true, wtb:{robu:'https://robu.in/product/dupont-jumper-wire-kit/', amazon:'https://www.amazon.com/Dupont-Jumper-Wire-Kit/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'headers', name:'40-pin Header Strips', cat:'proto', tier:1, note:'Male + female, 2.54mm, breakable', price:20, tags:['header','2.54mm'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Pin_header', verified:true, wtb:{robu:'https://robu.in/product/40-pin-header-strips/', amazon:'https://www.amazon.com/40-Pin-Header-Strips/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'perf5x7', name:'Perfboard 5×7cm', cat:'proto', tier:1, note:'Copper pads, single-sided', price:15, tags:['perfboard','PCB'], pairs:['headers'], datasheet:'https://en.wikipedia.org/wiki/Perfboard', verified:true, wtb:{robu:'https://robu.in/product/perfboard-5x7cm/', amazon:'https://www.amazon.com/Perfboard-5x7cm/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'smd-adapter', name:'SMD Adapter Boards', cat:'proto', tier:2, note:'SOP/SSOP/TSSOP to DIP', price:50, tags:['SMD','adapter'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/SMD_adapter', verified:true, wtb:{robu:'https://robu.in/product/smd-adapter-boards/', amazon:'https://www.amazon.com/SMD-Adapter-Boards/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'soic8-breakout', name:'SOIC-8 Breakout', cat:'proto', tier:2, note:'For EEPROMs and flash chips', price:20, tags:['SOIC8','breakout'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Breakout_board', verified:true, wtb:{robu:'https://robu.in/product/soic-8-breakout-board/', amazon:'https://www.amazon.com/SOIC-8-Breakout/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // MECHANICAL
  { id:'gear-motor', name:'Gear Motor TT (17–68 RPM)', cat:'mechanical', tier:1, note:'DC, 3–6V, plastic gearbox, ~150mA at load', price:80, tags:['DC','motor','gearbox','robot'], pairs:['l298n-mini','18650'], datasheet:'https://en.wikipedia.org/wiki/Gear_motor', verified:true, wtb:{robu:'https://robu.in/product/tt-gear-motor/', amazon:'https://www.amazon.com/TT-Gear-Motor/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'servo-sg90', name:'SG90 Micro Servo', cat:'mechanical', tier:1, note:'9g, 0–180°, 5V, 1.8kg·cm', price:90, tags:['servo','PWM','5V','arm'], pairs:['esp32-wroom','arduino-uno'], datasheet:'https://en.wikipedia.org/wiki/Servo_motor', verified:true, wtb:{robu:'https://robu.in/product/sg90-micro-servo/', amazon:'https://www.amazon.com/SG90-Micro-Servo/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'n20-motor', name:'N20 Micro Gear Motor', cat:'mechanical', tier:2, note:'Metal gearbox, 6V 100RPM', price:150, tags:['motor','N20','metal'], pairs:['l298n-mini'], datasheet:'https://en.wikipedia.org/wiki/Gear_motor', verified:true, wtb:{robu:'https://robu.in/product/n20-micro-gear-motor/', amazon:'https://www.amazon.com/N20-Micro-Gear-Motor/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'28byj48', name:'28BYJ-48 Stepper + ULN2003', cat:'mechanical', tier:2, note:'5V geared stepper motor', price:120, tags:['stepper','motor','5V'], pairs:['arduino-uno'], datasheet:'https://en.wikipedia.org/wiki/Stepper_motor', verified:true, wtb:{robu:'https://robu.in/product/28byj48-stepper-motor/', amazon:'https://www.amazon.com/28BYJ48-Stepper-Motor/dp/B07P8S2PP2', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  // MATERIAL
  { id:'copper-wire-1mm', name:'Copper Wire 1mm', cat:'material', tier:2, note:'Frame / structural bending, soft annealed', price:120, tags:['copper','frame','structural'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Copper_wire', verified:true, wtb:{robu:'https://robu.in/product/copper-wire-1mm/', amazon:'https://www.amazon.com/Copper-Wire-1mm/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
  { id:'copper-wire-07mm', name:'Copper Wire 0.7mm', cat:'material', tier:2, note:'Fine detail, pins, connections', price:90, tags:['copper','fine','pins'], pairs:[], datasheet:'https://en.wikipedia.org/wiki/Copper_wire', verified:true, wtb:{robu:'https://robu.in/product/copper-wire-0-7mm/', amazon:'https://www.amazon.com/Copper-Wire-0-7mm/dp/B08R5G3Z9D', ali:'https://www.aliexpress.com/item/32833524574.html'} },
];

export const REC_REASONS: Record<string, string> = {
  'esp32-wroom': 'Foundation for IoT projects with WiFi + Bluetooth, large community support',
  'esp32-c3': 'Compact RISC-V core with WiFi + BT 5.0, ideal for dedicated nodes',
  'oled-ssd1306': 'Essential display for visual feedback and sensor data visualization',
  'dht22': 'Reliable temperature and humidity sensor for weather monitoring',
  'bmp280': 'Pressure and altitude sensor with I2C/SPI interface',
  'mpu6050': '6-axis IMU for motion detection and orientation sensing',
  'hcsr04': 'Ultrasonic distance sensor for obstacle avoidance and robotics',
  'relay': 'Enables microcontroller to control high-power AC/DC devices',
  'l298n-mini': 'Dual H-bridge motor driver for DC motor control',
  'gear-motor': 'DC gear motors for robotics and mechanical projects',
  'bms-2s': 'Battery management system for safe 2S Li-ion pack charging',
  'tp4056-micro': 'Compact Li-ion battery charger with protection circuitry',
  'nrf24l01': '2.4GHz wireless transceiver for point-to-point communication',
  'rtl-sdr': 'Software-defined radio receiver for RF spectrum analysis',
  'res-kit': 'Comprehensive resistor assortment for circuit prototyping',
  'cap-kit': 'Essential capacitor kit for decoupling and filtering',
  'led-kit': 'LED assortment for indicators and visual feedback',
  'bb830': 'Full-size breadboard for solderless prototyping',
  'dupont-kit': 'Jumper wire kit for connecting components',
  'logic-shifter': 'Bidirectional voltage level converter for mixed logic systems',
  'lm2596': 'Adjustable buck converter for voltage regulation',
  'xl6009': 'Boost converter for stepping up voltage levels',
  '18650': 'High-capacity Li-ion rechargeable battery',
  'tft-st7735': 'Color TFT display for advanced UI projects',
  'rotenc': 'Rotary encoder for user input and navigation',
  'bme680': 'Environmental sensor with temperature, humidity, pressure, and VOC',
  'speaker-3w': 'Compact speaker for audio feedback and alerts',
  'ne555': 'Versatile timer IC for oscillators and timing circuits',
  'servo-sg90': 'Micro servo for precise angular positioning',
  'copper-wire-1mm': 'Structural wire for custom enclosures and frames',
  'hc05': 'Classic Bluetooth module for smartphone connectivity',
  '433mhz-pair': 'Low-cost RF transmitter/receiver pair for simple wireless control'
};

export const GOAL_PRIORITY_IDS: Record<string, string[]> = {
  iot:      ['bb830','dupont-kit','esp32-wroom','res-kit','cap-kit','led-kit','oled-ssd1306','dht22','bmp280','relay','tp4056-micro','18650','lm2596'],
  robotics: ['bb830','dupont-kit','esp32-c3','res-kit','cap-kit','l298n-mini','gear-motor','hcsr04','18650','bms-2s','xl6009','mpu6050','servo-sg90'],
  rf:       ['bb830','dupont-kit','esp32-wroom','res-kit','cap-kit','433mhz-pair','nrf24l01','hc05','18650','tp4056-micro','rtl-sdr'],
  display:  ['bb830','dupont-kit','esp32-wroom','res-kit','cap-kit','oled-ssd1306','rotenc','tft-st7735','18650','tp4056-micro'],
  general:  ['bb830','dupont-kit','res-kit','cap-kit','led-kit','esp32-wroom','oled-ssd1306','dht22','ne555','relay','tp4056-micro','18650'],
};

export const PROJECT_TEMPLATES: Record<string, string[]> = {
  'weather station': ['esp32-wroom','dht22','bmp280','oled-ssd1306','bb830','dupont-kit'],
  'line follower': ['arduino-uno','l298n-mini','gear-motor','gear-motor','hcsr04','18650','bb830','dupont-kit'],
  'smart home hub': ['esp32-wroom','relay','dht22','nrf24l01','bb830','dupont-kit']
};

export const STARTER_KITS = [
  {
    id: 'kit-weather',
    name: 'Weather Station Kit',
    desc: 'Everything you need to build a WiFi-connected weather station with OLED display.',
    tags: ['weather', 'iot', 'sensor'],
    items: [
      { id: 'esp32-wroom', qty: 1 },
      { id: 'dht22', qty: 1 },
      { id: 'bmp280', qty: 1 },
      { id: 'oled-ssd1306', qty: 1 },
      { id: 'bb830', qty: 1 },
      { id: 'dupont-kit', qty: 1 },
      { id: 'res-kit', qty: 1 }
    ]
  },
  {
    id: 'kit-robot',
    name: 'Basic Robot Kit',
    desc: 'Build a simple 2-wheel robot with obstacle avoidance.',
    tags: ['robot', 'motor', 'arduino'],
    items: [
      { id: 'arduino-uno', qty: 1 },
      { id: 'l298n-mini', qty: 1 },
      { id: 'gear-motor', qty: 2 },
      { id: 'hcsr04', qty: 1 },
      { id: '18650', qty: 2 },
      { id: 'bb830', qty: 1 },
      { id: 'dupont-kit', qty: 1 }
    ]
  },
  {
    id: 'kit-clock',
    name: 'Digital Clock Kit',
    desc: 'A simple digital clock using a 4-digit 7-segment display.',
    tags: ['clock', 'display', 'beginner'],
    items: [
      { id: 'esp8266-nodemcu', qty: 1 },
      { id: 'tm1637', qty: 1 },
      { id: 'bb830', qty: 1 },
      { id: 'dupont-kit', qty: 1 }
    ]
  }
];
